### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by krishnaanand1896** [ha7ilm/smallrx#5]
Sir how to modify the code if we are working with a prerecorded dat file?

**Comment by ha7ilm** [comment]
There is an example with `cat` in the `README`.

**Comment by krishnaanand1896** [comment]
http://www.aaronscher.com/wireless_com_SDR/RTL_SDR_AM_spectrum_demod.html
Sir I have used the file specified in the link and the sampling rate is 2.5 Mhz .
cat FMcapture1.iq | ./rx 100122000 100300000 f > /mnt/d/ac.txt-This is the command used .But the output is noisy.
And one more doubt sir should we do decimation in two steps?If yes where is decimate_factor used after demodulation?

**Comment by ha7ilm** [comment]
You can watch the related talk and edit the code accordingly, if you need to change the filtering and decimation part. The code is very short, and in the talk it is explained how it works. For a more flexible command line tool, check out `csdr`.

**Comment by krishnaanand1896** [comment]
Thanks, I'll check it out.

**Comment by krishnaanand1896** [comment]
Respected Sir
I am sorry for disturbing you again.I have one more doubt uranium is a file
stored in your device or is it generated randomly?
I tried with my file its again full of noise.I am using audacity for
listening .
Thank you

**Comment by ha7ilm** [comment]
You can use Wikipedia to know more about `/dev/urandom`. Uranium is a chemical element, not related to the project.

**Comment by krishnaanand1896** [comment]
Thanks for your response sir I was asking about urandom sir,typing error,
sorry for that

**Comment by krishnaanand1896** [comment]
Respected Sir
One more clarification how do we select the amfm by and decimation
transition bw.
Thank you

**Comment by krishnaanand1896** [comment]
Respected Sir
I tried with a downloaded file FMcapture1.dat with sampling frequency 2.5
mhz centre frequency 100.122 mhz and receiver frequency 100.3 mhz.
How to modify amfm bw and decimation transition bandwidth according to the
file.If you have tried with any file can you let me know which one is it.
Also your comment was to perform decimation in 2 steps,one before and one
after demodulation,after demodulation,where to use this decimation,
Waiting for your valuable respinse.
Thank you

**Comment by krishnaanand1896** [comment]
Respected Sir
I have captured a signal using RTL SDR at the same frequency and sampling
rate and have done every step exactly the same as yours.But my output is
noise.
Kindly help me sir

**Comment by ha7ilm** [comment]
Sorry, I am unable to provide further support on this case, due to lack of time.

**Comment by krishnaanand1896** [comment]
Respected sir
Sorry sir ...Thanks for your reply..
Thank you

**Comment by krishnaanand1896** [comment]
Respected Sir
Thank you for your response.I have some more doubts.
Is it necessary to perform decimation in two steps?If yes where is
decimate_factor used after demodulation?
Thank you
Krishna Anand

**Comment by ha7ilm** [comment]
Sorry, I am unable to provide further support on this case, due to lack of time.
